se sube version y codemagic update

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -1,43 +1,27 @@
-workflows:
-  android-workflow:
+definitions:
+  scripts:
+    - &flutter_packages
+      name: Get Flutter packages
+      script: |
+        flutter packages pub get
     
-    name: MyPets Android
-    
-    environment:
-      flutter: stable
-      xcode: latest
-      cocoapods: default
-      # android_signing:
-      #   - keystore_reference
-      groups:
-        - keystore_credentials
-        - discord_credentials
-        - firebase_credentials
-        # - keystore_reference
-      # android_signing:
-      #   - keystore: keystore_reference
-      #     keystore_environment_variable: THIS_KEYSTORE_PATH_ON_DISK_1
-      #     keystore_password_environment_variable: THIS_KEYSTORE_PASSWORD_1
-      #     key_alias_environment_variable: THIS_KEY_ALIAS_1
-      #     key_password_environment_variable: THIS_KEY_PASSWORD_1
-      
-    scripts:
-    - name: Set up keystore
+    - &android_set_keys
+      name: Set up keystore
       script: |
           echo $CM_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH
-    - name: Set up local.properties
+    
+    - &android_set_local_properties
+      name: Set up local.properties
       script: | 
         echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
-    - name: Get Flutter packages
-      script: | 
-        flutter packages pub get
-    # - name: Flutter analyze
-    #   script: | 
-    #       flutter analyze
-    - name: Build APK with Flutter
+    
+    - &flutter_build_apk_prod
+      name: Build APK with Flutter
       script: | 
         flutter build apk --flavor prod --release
-    - name: Create a changelog
+
+    - &create_changelog
+      name: Create a changelog
       script: | 
         if [[ -z ${CM_PREVIOUS_COMMIT} ]]
           then
@@ -45,14 +29,16 @@ workflows:
           else
             echo "$(git-changelog generate --previous-commit $CM_PREVIOUS_COMMIT)" | tee release_notes.txt
         fi
-        
-    
-    artifacts:
-      - app/build/outputs/**/**/*.apk
-      - build/app/outputs/flutter-apk/app-prod-release.apk
-      - flutter_drive.log
 
-    publishing:
+    email_release: &email_release
+      email:
+        recipients:
+          - maidana1454@gmail.com
+        notify:
+          success: true
+          failure: true
+
+    publish_firebase_android: &publish_firebase_android
       firebase:
         firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
         android:
@@ -60,8 +46,9 @@ workflows:
           groups:
             - android_testers
           artifact_type: 'apk'
-      scripts:
-      - name: Discord notification
+    
+    - &discord_notification_build_android_qa
+      name: Discord notification
         script: | 
           set -ex
           APP_LINK=$(echo $CM_ARTIFACT_LINKS | jq -r '.[] | select(.name=="app-release.apk") | .url')
@@ -77,16 +64,36 @@ workflows:
           
           # Publish the notification
           curl -H "Content-Type: multipart/form-data" \
-          -F 'payload_json={"username" : "android-bot", "content": "**Commit:** `'"$COMMIT"'`\n\n**Commit message:** '"$COMMIT_MESSAGE"'\n\n**Branch:** '"$CM_BRANCH"'\n\n**Author:** '"$AUTHOR"'\n\n**Artifacts: **\n\n'"$APP_LINK"'\n\n"}' \
+          -F 'payload_json={"username" : "Aki-Android", "content": "**Commit:** `'"$COMMIT"'`\n\n**Commit message:** '"$COMMIT_MESSAGE"'\n\n**Branch:** '"$CM_BRANCH"'\n\n**Author:** '"$AUTHOR"'\n\n**Artifacts: **\n\n'"$APP_LINK"'\n\n"}' \
           -F "file1=@release_notes.txt" \
           $WEBHOOK_URL
-      email:
-        recipients:
-          - maidana1454@agmail.com
-        notify:
-          success: true
-          failure: true
-    
+
+workflows:
+  firebase_android_qa:
+    name: MyPets Qa
+    environment:
+      flutter: stable
+      xcode: latest
+      cocoapods: default
+      # android_signing:
+      #   - keystore_reference
+      groups:
+        - keystore_credentials
+        - discord_credentials
+        - firebase_credentials
+    scripts:
+      - *android_set_keys
+      - *android_set_local_properties
+      - *flutter_packages
+      - *flutter_build_apk_prod
+      - *create_changelog
+
+    artifacts:
+      - app/build/outputs/**/**/*.apk 
+      - build/app/outputs/flutter-apk/app-release.apk
+      - app/build/outputs/**/*.aab
+      - build/app/outputs/bundle/release/app-release.aab
+
     triggering:
       events:
         - push
@@ -95,6 +102,102 @@ workflows:
           include: true
           source: true
       cancel_previous_builds: true
+
+    publishing:
+      <<: *email_release
+      <<: *publish_firebase_android
+      <<: *publish_firebase_android
+      scripts:
+        - *discord_notification_build_android_qa
+
+  # android-workflow:
+  #   name: MyPets Android
+  #   environment:
+  #     flutter: stable
+  #     xcode: latest
+  #     cocoapods: default
+  #     # android_signing:
+  #     #   - keystore_reference
+  #     groups:
+  #       - keystore_credentials
+  #       - discord_credentials
+  #       - firebase_credentials
+  #       # - keystore_reference
+      
+  #   scripts:
+  #   - name: Set up keystore
+  #     script: |
+  #         echo $CM_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH
+  #   - name: Set up local.properties
+  #     script: | 
+  #       echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
+  #   - name: Get Flutter packages
+  #     script: | 
+  #       flutter packages pub get
+  #   # - name: Flutter analyze
+  #   #   script: | 
+  #   #       flutter analyze
+  #   - name: Build APK with Flutter
+  #     script: | 
+  #       flutter build apk --flavor prod --release
+  #   - name: Create a changelog
+  #     script: | 
+  #       if [[ -z ${CM_PREVIOUS_COMMIT} ]]
+  #         then
+  #           echo "No finished builds found to generate changelog" | tee release_notes.txt
+  #         else
+  #           echo "$(git-changelog generate --previous-commit $CM_PREVIOUS_COMMIT)" | tee release_notes.txt
+  #       fi
+        
+    
+  #   artifacts:
+  #     - app/build/outputs/**/**/*.apk
+  #     - build/app/outputs/flutter-apk/app-prod-release.apk
+  #     - flutter_drive.log
+
+  #   publishing:
+  #     firebase:
+  #       firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
+  #       android:
+  #         app_id: 1:212788224879:android:85e1b0e58b07f594a3fe9a 
+  #         groups:
+  #           - android_testers
+  #         artifact_type: 'apk'
+  #     scripts:
+  #     - name: Discord notification
+  #       script: | 
+  #         set -ex
+  #         APP_LINK=$(echo $CM_ARTIFACT_LINKS | jq -r '.[] | select(.name=="app-release.apk") | .url')
+        
+  #         # Get first 7 digits of commit number
+  #         COMMIT=$(echo "${CM_COMMIT}" | sed 's/^\(........\).*/\1/;q')
+
+  #         # Get commit message
+  #         COMMIT_MESSAGE=$(git log --format=%B -n 1 $CM_COMMIT)
+          
+  #         # Get commit author
+  #         AUTHOR=$(git show -s --format='%ae' $CM_COMMIT)
+          
+  #         # Publish the notification
+  #         curl -H "Content-Type: multipart/form-data" \
+  #         -F 'payload_json={"username" : "Aki-Android", "content": "**Commit:** `'"$COMMIT"'`\n\n**Commit message:** '"$COMMIT_MESSAGE"'\n\n**Branch:** '"$CM_BRANCH"'\n\n**Author:** '"$AUTHOR"'\n\n**Artifacts: **\n\n'"$APP_LINK"'\n\n"}' \
+  #         -F "file1=@release_notes.txt" \
+  #         $WEBHOOK_URL
+  #     email:
+  #       recipients:
+  #         - maidana1454@agmail.com
+  #       notify:
+  #         success: true
+  #         failure: true
+    
+  #   triggering:
+  #     events:
+  #       - push
+  #     branch_patterns:
+  #       - pattern: 'qa'
+  #         include: true
+  #         source: true
+  #     cancel_previous_builds: true
 # artifacts:
 #     - app/build/outputs/**/**/*.apk
 #     - build/app/outputs/flutter-apk/app-release.apk
